-
  version: '{build}'
  image: Visual Studio 2017 Preview
  cache: 
  - '%userprofile%\.nuget\packages -> appveyor.yml.cache'
  nuget:
    project_feed: true
    disable_publish_on_pr: true
  build_script:
  - ps: .\build.ps1
  test: off
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  deploy:
  - provider: NuGet
    server: https://www.myget.org/F/ublsharp/api/v2/package
    api_key:
      secure: lJMCPwGiDw8APCDOU7Wyjcr+MXV1VV2rC8AkX9dpk4lX+WGs29YCa1H0RxNy3tlI
    skip_symbols: true
    on:
      branch: master
-
  branches:
    only: 
      - /release.*/
  version: '{build}'
  image: Visual Studio 2017 Preview
  cache: 
  - '%userprofile%\.nuget\packages -> appveyor.yml.cache'
  nuget:
    project_feed: true
    disable_publish_on_pr: true
  build_script:
  - ps: .\build.ps1 -NuGet
  test: off
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: 0Idnj65UTCZqpVUDI/8Y8/mMLJ3fTLbknyKgAF3A5jVN2M2vGCcG3EDWh4GyUIdt
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: voP35JF5npCVqWOFWeEUQnjC+qXk6QAPcIAxRDcgaaB9NovL05c6YjavzQepCA8b
    artifact: NuGet
    draft: true
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true
